export const enviroments = {
  getAllDoctorPosition: "https://fmptechnology.from-me.org:45333/api/api/v1/doctorposition/all",
  createDoctorPosition: "https://fmptechnology.from-me.org:45333/api/api/v1/doctorposition/create",
  getAllDoctor: "https://fmptechnology.from-me.org:45333/api/api/v1/doctor/all",
  createDoctor: "https://fmptechnology.from-me.org:45333/api/api/v1/doctor/create",
  deleteDoctor: "https://fmptechnology.from-me.org:45333/api/api/v1/doctor/remove",
  updateDoctor: "https://fmptechnology.from-me.org:45333/api/api/v1/doctor/update",
  getPatient: "https://fmptechnology.from-me.org:45333/api/api/v1/patient/all",
  createPatient: "https://fmptechnology.from-me.org:45333/api/api/v1/patient/create",
  updatePatient: "https://fmptechnology.from-me.org:45333/api/api/v1/patient/update",
  deletePatient: "https://fmptechnology.from-me.org:45333/api/api/v1/patient/remove",
  createEmployee: "https://fmptechnology.from-me.org:45333/api/api/v1/employee/create",
  getAllEmployeePosition: "https://fmptechnology.from-me.org:45333/api/api/v1/employeeposition/all",
  deleteEmployee: "https://fmptechnology.from-me.org:45333/api/api/v1/employee/remove",
  createEmployeePosition:
    "https://fmptechnology.from-me.org:45333/api/api/v1/employeeposition/create",
  createPersonAddress: "https://fmptechnology.from-me.org:45333/api/api/v1/personaddress/create",
  deletePersonAddress: "https://fmptechnology.from-me.org:45333/api/api/v1/personaddress/remove",
  updatePersonAddress: "https://fmptechnology.from-me.org:45333/api/api/v1/personaddress/update",
  getAllPersonAddress: "https://fmptechnology.from-me.org:45333/api/api/v1/personaddress/all",
};
